name: 'Pull request bot synchronizes two services: GitHub, Moodle. Script 2'
description: 'Takes data from two services and compares it, writes the result to Github (configured)'

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: docker run -v ${{ env.PR_BOT_CONFIG_PATH }}:/config -e COURSE_ID="${{env.COURSE_ID}}" -e CM_ID="${{env.CM_ID}}" -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="${{env.GITHUB_PR_REGEX}}" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ env.MOODLE_ACCESS_TOKEN }}" --rm fox1209/gm_scripts:1.0.2  python main.py script2
      shell: bash