name: 'Pull request bot synchronizes two services: GitHub, Moodle. Script 2'
description: 'Takes data from two services and compares it, writes the result to Github (configured)'

branding:
  icon: 'book'  
  color: 'gray-dark'

runs:
  steps:
    - 
      name: Check env
      uses: andymckay/cancel-action@0.2
      if: "${{ env.COURSE_ID == '' || env.CM_ID == '' || github.repository == '' || env.GITHUB_PR_REGEX == ''}}"
    -
      name: Run script
      run: docker run -e COURSE_ID="${{env.COURSE_ID}}" -e CM_ID="${{env.CM_ID}}" -e GITHUB_REPO="${{ github.repository }}" -e GITHUB_PR_REGEX="${{env.GITHUB_PR_REGEX}}" -e GITHUB_ACCESS_TOKEN="${{ github.token }}" -e MOODLE_ACCESS_TOKEN="${{ secrets.MOODLE_ACCESS_TOKEN }}" --rm fox1209/gm_scripts:1.0.0  python main.py script2
